In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
voc_size = 10000

In [4]:
# One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[7016, 9395, 9953, 722],
 [7016, 9395, 9953, 6539],
 [7016, 9689, 9953, 5367],
 [6543, 949, 416, 6198, 4313],
 [7633, 7016, 9532, 9953, 1523],
 [102, 6277, 6398, 6198]]

In [5]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7016 9395 9953  722]
 [   0    0    0    0 7016 9395 9953 6539]
 [   0    0    0    0 7016 9689 9953 5367]
 [   0    0    0 6543  949  416 6198 4313]
 [   0    0    0 7633 7016 9532 9953 1523]
 [   0    0    0    0  102 6277 6398 6198]]


In [7]:
# Feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step


array([[[ 0.04111798,  0.00519501, -0.03441   , -0.04725652,
          0.02588474,  0.02797022, -0.00784711, -0.00937001,
          0.04859963,  0.00768597],
        [ 0.04111798,  0.00519501, -0.03441   , -0.04725652,
          0.02588474,  0.02797022, -0.00784711, -0.00937001,
          0.04859963,  0.00768597],
        [ 0.04111798,  0.00519501, -0.03441   , -0.04725652,
          0.02588474,  0.02797022, -0.00784711, -0.00937001,
          0.04859963,  0.00768597],
        [ 0.04111798,  0.00519501, -0.03441   , -0.04725652,
          0.02588474,  0.02797022, -0.00784711, -0.00937001,
          0.04859963,  0.00768597],
        [-0.02340556, -0.03394895,  0.02906286, -0.02667937,
         -0.03862231, -0.04290594,  0.02134097, -0.00602589,
          0.04631826, -0.01145693],
        [-0.02476127, -0.02768986, -0.04923062,  0.04573641,
          0.04712388, -0.01275434,  0.00674571, -0.0455046 ,
         -0.03851507, -0.00212479],
        [-0.01328377, -0.02753915, -0.00586788,  0.0